### ISSUE TITLE
Consider dual licencing under CERN-OHL-S?

### ISSUE THREAD

**Issue by julianstirling** [solidboredom/constructive#5]
Hi,

This looks like a really cool project. I get that it is GPL licensed to make it strongly reciprocal. It does make it unclear if it can be used in open hardware projects that are also strongly reciprocal. The main strongly reciprocal open hardware license is the CERN  OHL-S (v2).

Would you consider dual licensing for open hardware use?

**Comment by solidboredom** [comment]
Yes, absolutely.
I did know anything about the OHL-S (v2). I will try to figure out what it is about. i do not think there will be a Problem

**Comment by solidboredom** [comment]
i have asked a question about it on the openscad mailing list, of course you are very welcome to clarify things i am really new to this license

**Comment by julianstirling** [comment]
I can't see the message on the mailing list archive. (I don't have the list come through to my email, I used to respond in the forum while that still worked.)

Can you ask the question here or email me at julian [at] julianstirling.co.uk?

**Comment by solidboredom** [comment]
Hello Julian, could you check you spam folder?
I have forwarded you two messages from Openscad List to you email.
would be great to hear your take on this, to remove the last doubt.
Thanks!

**Comment by julianstirling** [comment]
Wonderful, thanks.

Also not a lawyer... but here is how I understand everything.

I agree with Torsten that compatibility with OpenSCAD's isn't really essential. In the same way you can use OpenSCAD to write your own proprietary hardware, or hardware under any license. You just can't distribute a modified version of OpenSCAD itself without releasing the code under GPL.

As you wrote the code you can release it under multiple licenses. Some programs (such as FFTW the Fourier Transform Library) licence things as GPL and then will do paid for licenses with other companies that don't want to have abide by GPL terms. So there is certainly no reason why you can't release your own code under two licenses, you just can't relicense other people's code from GPL to something else.

Where it come to the CERN OHL-S, this is a reciprocal license specifically designed for hardware. Using GPL for hardware is somewhat iffy as the license repeatedly talks about the "software". So projects such as the [OpenFlexure Microscope](openflexure.org) release their code under a CERN license.

In the case of using a library you need license compatibility. My understanding is that CERN OHL and GPL are incompatible, even though they are both reciprocal licenses. As this library is designed to help people create hardware it would be really nice if it can be used Open Hardware projects that use the CERN OHL. It makes sense to also license it as GPL as there are still some hardware projects such as RepRap using GPL.

If you wanted constructive to be useable for any project under other licenses, but still wanted changes of constructive to be themselves released openly. You might want to consider changing the licenses to LGPL and CERN OHL-W. These are weakly reciprocal licenses, allowing library use for any project, but changes to the library must be released under the same license.

**Comment by solidboredom** [comment]
i have made it doallicensed: GPL 2.0 CERN-OHL-W

**Comment by julianstirling** [comment]
You sir are a gentleman and a scholar

**Comment by julianstirling** [comment]
Oops, need another comment to close as completed. Thanks again

**Comment by solidboredom** [comment]
cool. happy to know more people can use it
